### ISSUE TITLE
Sometimes bots dont respawn

### ISSUE THREAD

**Issue by Zetz512** [Hedgefog/cs-halloween-mod#53]
I think its happen when bots entering too late in a game was already started... if i dont exec amx_cvar sv_restartround 1
they dont respawn, after that all works fine

**Comment by Hedgefog** [comment]
What bots do you use?

**Comment by Zetz512** [comment]
Ohhh hi! that was so long xd, sry, ok, ehm that time i used yapb latest version from yapb.ru

**Comment by Hedgefog** [comment]
It looks like this problem is related to yapb, I have the same issue, but it is not possible to make a fix on the mod side. 
Bots should emit `joinclass` and `menuselect` client commands somehow, other bots do it, but yapb didn't. Current respawn implementation is the most stable way to do it unfortunately there are no real alternatives that work as well.

**Comment by jeefo** [comment]
Should be resolved in latest build yapb.
